services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - webapp-code:/var/www
    env_file:
      - .env
    networks:
      - app-network

  web:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - webapp-code:/var/www:ro
    depends_on:
      - app
    networks:
      - app-network

volumes:
  webapp-code:


networks:
  app-network:
    driver: bridge
